export type Recipe = {
  id: string;
  title: string;
  meal: "Desayuno" | "Almuerzo" | "Cena" | "Merienda";
  ingredients: string[];
  description: string;
  steps: string[];
  minutes: number;
  cost: "Económica" | "Media";
  iron: string;
  kcal: number;
  protein: string;
  vitaminC: string;
  tip: string;
  video: string;
};

const yt = (q: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

export const ingredientOptions = [
  "sangrecita",
  "hígado",
  "bazo",
  "carne de res",
  "pollo",
  "pescado",
  "huevo",
  "lentejas",
  "frejoles",
  "garbanzos",
  "quinua",
  "espinaca",
  "beterraga",
  "brócoli",
  "zanahoria",
  "tomate",
  "pimiento rojo",
  "naranja",
  "limón",
  "papa",
  "arroz",
  "avena",
  "camote",
] as const;

export const recipes: Recipe[] = [
  {
    id: "sangrecita-papa",
    title: "Sangrecita saltada con papa y culantro",
    meal: "Almuerzo",
    ingredients: ["sangrecita", "papa", "limón", "arroz"],
    description:
      "El plato con más hierro del recetario peruano. Rápido, barato y recomendado en programas contra la anemia infantil.",
    steps: [
      "Dora ajo y cebolla picada en poco aceite.",
      "Agrega la sangrecita en cubos y cocina 6 minutos moviendo.",
      "Suma papa sancochada, culantro y sal.",
      "Sirve con arroz y unas gotas de limón.",
    ],
    minutes: 20,
    cost: "Económica",
    iron: "29 mg por porción",
    kcal: 340,
    protein: "26 g",
    vitaminC: "20 mg",
    tip: "Acompaña con limonada o jugo de naranja para absorber más hierro.",
    video: yt("receta sangrecita de pollo para la anemia"),
  },
  {
    id: "higado-encebollado",
    title: "Hígado encebollado con arroz",
    meal: "Almuerzo",
    ingredients: ["hígado", "tomate", "arroz", "limón"],
    description: "Hierro hemo concentrado, listo en menos de media hora.",
    steps: [
      "Marina el hígado en limón, ajo y comino 10 minutos.",
      "Saltea a fuego alto 3 minutos por lado.",
      "Agrega cebolla y tomate en tiras, cocina 4 minutos.",
      "Sirve con arroz y ensalada fresca.",
    ],
    minutes: 25,
    cost: "Económica",
    iron: "9,8 mg por porción",
    kcal: 520,
    protein: "34 g",
    vitaminC: "28 mg",
    tip: "1 o 2 veces por semana es suficiente.",
    video: yt("receta higado encebollado peruano"),
  },
  {
    id: "bazo-guisado",
    title: "Guiso de bazo con verduras",
    meal: "Almuerzo",
    ingredients: ["bazo", "zanahoria", "tomate", "papa"],
    description: "Vísceras económicas guisadas a fuego lento con verduras.",
    steps: [
      "Corta el bazo en cubos y sella con ajo.",
      "Añade tomate, zanahoria y papa.",
      "Cocina tapado 20 minutos con un poco de agua.",
    ],
    minutes: 35,
    cost: "Económica",
    iron: "12 mg por porción",
    kcal: 400,
    protein: "28 g",
    vitaminC: "25 mg",
    tip: "Sirve caliente con perejil fresco encima.",
    video: yt("receta guiso de bazo de res"),
  },
  {
    id: "lentejas-pimiento",
    title: "Guiso de lentejas con pimiento rojo",
    meal: "Almuerzo",
    ingredients: ["lentejas", "pimiento rojo", "zanahoria", "arroz"],
    description: "Hierro vegetal potenciado con la vitamina C del pimiento.",
    steps: [
      "Cocina las lentejas remojadas 25 minutos.",
      "Aparte, sofríe ajo, cebolla, zanahoria y pimiento rojo.",
      "Une todo y deja espesar 10 minutos.",
    ],
    minutes: 40,
    cost: "Económica",
    iron: "6,6 mg por plato",
    kcal: 420,
    protein: "18 g",
    vitaminC: "95 mg",
    tip: "Evita café o té hasta 1 hora después.",
    video: yt("receta guiso de lentejas con pimiento rojo"),
  },
  {
    id: "espinaca-garbanzos",
    title: "Ensalada tibia de espinaca, garbanzos y huevo",
    meal: "Cena",
    ingredients: ["espinaca", "garbanzos", "huevo", "limón"],
    description: "Ligera, rápida y muy rica en hierro no hemo.",
    steps: [
      "Saltea la espinaca 2 minutos.",
      "Mezcla con garbanzos cocidos y huevo duro en cuartos.",
      "Aliña con limón, aceite y sal.",
    ],
    minutes: 15,
    cost: "Económica",
    iron: "5,4 mg por plato",
    kcal: 380,
    protein: "19 g",
    vitaminC: "45 mg",
    tip: "Agrega una cucharada de semillas de zapallo.",
    video: yt("ensalada de espinaca garbanzos y huevo receta"),
  },
  {
    id: "pescado-quinua",
    title: "Pescado a la plancha con quinua y brócoli",
    meal: "Almuerzo",
    ingredients: ["pescado", "quinua", "brócoli", "limón"],
    description: "Hierro, omega 3 y vitamina B12 en un solo plato.",
    steps: [
      "Sazona el filete con limón, ajo y sal.",
      "Plancha 3 minutos por lado.",
      "Sirve con quinua graneada y brócoli al vapor.",
    ],
    minutes: 30,
    cost: "Media",
    iron: "4,8 mg por plato",
    kcal: 460,
    protein: "32 g",
    vitaminC: "70 mg",
    tip: "Lava bien la quinua antes de cocerla.",
    video: yt("receta pescado con quinua y brocoli"),
  },
  {
    id: "batido-beterraga",
    title: "Batido de beterraga, naranja y avena",
    meal: "Desayuno",
    ingredients: ["beterraga", "naranja", "avena"],
    description: "Desayuno refrescante con mucha vitamina C.",
    steps: [
      "Licúa beterraga cocida con jugo de naranja.",
      "Agrega avena y un toque de kion.",
      "Sirve al instante.",
    ],
    minutes: 10,
    cost: "Económica",
    iron: "3,2 mg por vaso",
    kcal: 250,
    protein: "7 g",
    vitaminC: "110 mg",
    tip: "Tómalo recién preparado.",
    video: yt("batido de beterraga naranja y avena para la anemia"),
  },
  {
    id: "estofado-carne-frejoles",
    title: "Estofado de carne con frejoles",
    meal: "Almuerzo",
    ingredients: ["carne de res", "frejoles", "zanahoria", "tomate"],
    description: "Combina hierro hemo y no hemo en una sola olla.",
    steps: [
      "Sella la carne en trozos.",
      "Agrega tomate, zanahoria y frejoles cocidos.",
      "Cocina a fuego lento 30 minutos.",
    ],
    minutes: 50,
    cost: "Media",
    iron: "7,5 mg por porción",
    kcal: 540,
    protein: "35 g",
    vitaminC: "38 mg",
    tip: "Cocinar en olla de hierro suma hierro al guiso.",
    video: yt("receta estofado de carne con frejoles"),
  },
  {
    id: "tortilla-espinaca",
    title: "Tortilla de espinaca y huevo",
    meal: "Cena",
    ingredients: ["espinaca", "huevo", "tomate"],
    description: "Cena en 12 minutos con lo que ya tienes en casa.",
    steps: [
      "Bate 2 huevos con sal.",
      "Añade espinaca picada y tomate en cubos.",
      "Cocina a fuego medio 5 minutos por lado.",
    ],
    minutes: 12,
    cost: "Económica",
    iron: "3,8 mg",
    kcal: 280,
    protein: "16 g",
    vitaminC: "22 mg",
    tip: "Acompaña con rodajas de naranja de postre.",
    video: yt("tortilla de espinaca y huevo receta"),
  },
  {
    id: "avena-hierro",
    title: "Avena cremosa con naranja y maní",
    meal: "Desayuno",
    ingredients: ["avena", "naranja"],
    description: "Desayuno barato que se prepara mientras te alistas.",
    steps: [
      "Cocina avena en agua 6 minutos.",
      "Endulza con poca panela y agrega maní picado.",
      "Sirve con gajos de naranja.",
    ],
    minutes: 10,
    cost: "Económica",
    iron: "2,8 mg",
    kcal: 300,
    protein: "9 g",
    vitaminC: "60 mg",
    tip: "Evita tomar leche junto a la avena si buscas más hierro.",
    video: yt("avena con naranja desayuno saludable"),
  },
  {
    id: "pollo-camote",
    title: "Pollo guisado con camote y brócoli",
    meal: "Almuerzo",
    ingredients: ["pollo", "camote", "brócoli", "zanahoria"],
    description: "Guiso suave, ideal para niños y adultos mayores.",
    steps: [
      "Dora el pollo trozado.",
      "Agrega camote y zanahoria en cubos.",
      "Termina con brócoli al vapor.",
    ],
    minutes: 35,
    cost: "Media",
    iron: "3,5 mg",
    kcal: 470,
    protein: "30 g",
    vitaminC: "80 mg",
    tip: "Usa también el hígado de pollo si lo tienes.",
    video: yt("pollo guisado con camote receta"),
  },
  {
    id: "quinua-atomatada",
    title: "Quinua atomatada con huevo frito",
    meal: "Cena",
    ingredients: ["quinua", "tomate", "huevo", "pimiento rojo"],
    description: "Vegetariana, rendidora y con buena dosis de hierro.",
    steps: [
      "Sofríe tomate y pimiento con ajo.",
      "Agrega quinua cocida y mezcla.",
      "Corona con un huevo frito.",
    ],
    minutes: 25,
    cost: "Económica",
    iron: "4,2 mg",
    kcal: 410,
    protein: "17 g",
    vitaminC: "65 mg",
    tip: "Un chorrito de limón al final mejora la absorción.",
    video: yt("quinua atomatada receta peruana"),
  },
  {
    id: "frejoles-arroz",
    title: "Frejoles con arroz y ensalada de tomate",
    meal: "Almuerzo",
    ingredients: ["frejoles", "arroz", "tomate", "limón"],
    description: "El clásico combo peruano, completo y muy barato.",
    steps: [
      "Cocina los frejoles remojados con ajo y cebolla.",
      "Sirve con arroz blanco.",
      "Acompaña con ensalada de tomate y limón.",
    ],
    minutes: 45,
    cost: "Económica",
    iron: "5 mg",
    kcal: 500,
    protein: "20 g",
    vitaminC: "35 mg",
    tip: "La ensalada con limón es clave para el hierro vegetal.",
    video: yt("frejoles con arroz receta peruana"),
  },
  {
    id: "higado-pollo-pure",
    title: "Puré de papa con hígado de pollo",
    meal: "Cena",
    ingredients: ["hígado", "papa", "zanahoria"],
    description: "Textura suave, perfecta para niños pequeños.",
    steps: [
      "Sancocha papa y haz un puré.",
      "Saltea hígado de pollo y pícalo fino.",
      "Mezcla y sirve tibio.",
    ],
    minutes: 25,
    cost: "Económica",
    iron: "8 mg",
    kcal: 360,
    protein: "22 g",
    vitaminC: "18 mg",
    tip: "Ofrece fruta cítrica de postre.",
    video: yt("pure de papa con higado de pollo para niños"),
  },
  {
    id: "jugo-espinaca-naranja",
    title: "Refresco de espinaca, naranja y beterraga",
    meal: "Merienda",
    ingredients: ["espinaca", "naranja", "beterraga", "limón"],
    description: "Merienda ligera para sumar hierro y vitamina C.",
    steps: ["Licúa todo con agua fría.", "Cuela si prefieres y sirve al momento."],
    minutes: 8,
    cost: "Económica",
    iron: "2,5 mg",
    kcal: 150,
    protein: "4 g",
    vitaminC: "120 mg",
    tip: "No lo mezcles con lácteos.",
    video: yt("jugo de espinaca naranja y beterraga"),
  },
  {
    id: "causa-atun",
    title: "Causa de papa con pescado y espinaca",
    meal: "Cena",
    ingredients: ["papa", "pescado", "espinaca", "limón"],
    description: "Fría, rendidora y fácil de llevar.",
    steps: [
      "Prensa papa amarilla con limón y ají.",
      "Rellena con pescado desmenuzado y espinaca.",
      "Refrigera 20 minutos antes de servir.",
    ],
    minutes: 30,
    cost: "Media",
    iron: "3,6 mg",
    kcal: 390,
    protein: "24 g",
    vitaminC: "40 mg",
    tip: "Ideal para lonchera escolar.",
    video: yt("causa rellena de atun receta"),
  },
];

export type DayPlan = {
  day: string;
  desayuno: string;
  almuerzo: string;
  cena: string;
};

export const weeklyPlan: DayPlan[] = [
  { day: "Lunes", desayuno: "avena-hierro", almuerzo: "lentejas-pimiento", cena: "tortilla-espinaca" },
  { day: "Martes", desayuno: "batido-beterraga", almuerzo: "higado-encebollado", cena: "quinua-atomatada" },
  { day: "Miércoles", desayuno: "avena-hierro", almuerzo: "sangrecita-papa", cena: "espinaca-garbanzos" },
  { day: "Jueves", desayuno: "jugo-espinaca-naranja", almuerzo: "pollo-camote", cena: "higado-pollo-pure" },
  { day: "Viernes", desayuno: "batido-beterraga", almuerzo: "pescado-quinua", cena: "causa-atun" },
  { day: "Sábado", desayuno: "avena-hierro", almuerzo: "frejoles-arroz", cena: "tortilla-espinaca" },
  { day: "Domingo", desayuno: "jugo-espinaca-naranja", almuerzo: "estofado-carne-frejoles", cena: "espinaca-garbanzos" },
];

export const recipeById = (id: string) => recipes.find((r) => r.id === id)!;
